CREATE TABLE websites (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    url VARCHAR(255) NOT NULL,
    mail VARCHAR(255),
    hash VARCHAR(255) NOT NULL,
    host VARCHAR(255) NOT NULL,
    port INT NOT NULL,
    user VARCHAR(255) NOT NULL,
    pass VARCHAR(255),
    path VARCHAR(255) NOT NULL,
    updates INT DEFAULT 0,
    type VARCHAR(255) NOT NULL,
    spam_api VARCHAR(255)
);
